server:
  port: 12741

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: sv
    url: jdbc:mysql://localhost:3306/jxc?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 1111
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  config: classpath:logback-spring.xml


